import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";
import RepositoryList from "../components/RepositoryList";
import useGitfetch from "../utils/useGitFetch";
import InfiniteScroll from "react-infinite-scroll-component";

export default function Home() {
  const [page, setPage] = useState(1);

  const { repositories, loading, error } = useGitfetch([page]);

  const nextPage = () => {
    setPage((prevPage) => prevPage + 1);
  };


  if (error) {
    return <div>Error fetching data</div>;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <div>
          <h2 className="header">Trending Repositories</h2>

          <InfiniteScroll
            dataLength={repositories.length}
            next={nextPage}
            hasMore={true}
            loader={<h4 className="loader">Loading...</h4>}
          >
            {repositories &&
              repositories.map((repository) => (
                <RepositoryList key={repository.id} repository={repository} />
              ))}
          </InfiniteScroll>
        </div>
      </>
    </div>
  );
}
